<?php
////////////////
// sie_authsetup messages.
////////////////
$labels['2fa_required'] = "It is required to set a second authentication factor before continuing.";
$labels['clientcertificateunavailable'] = "eID (Peru) digital certificate hasn't been presented.";
$labels['authenticatedcitizennotregistered'] = 'eID (Peru) authenticated citizen (NID: $nid) doesn\'t have a SIE account.';
$labels['clientcertificatelogout'] = "Warning: You have to ensure to close your browser completely to close the eID session.";
$labels['ssllinktext'] = "Login with eID";
$labels['ssllinkwarning'] = "Warning: This login alternative can be dangerous in shared computers";

////////////////
/// kolab_2fa overrides.
////////////////
/// ...
