<?php
$labels['username'] = 'Username';
$labels['accepttos'] = 'I accept the <a href="$urltos" target="_blank">terms and conditions</a> of the service';
$labels['password'] = 'Password';
$labels['confirmpassword'] = 'Confirm password';
$labels['activate'] = 'Activate account';
$labels['add2fa'] = 'Add authentication factor';
$labels['code'] = 'code';
$labels['activationtitle'] = 'ACTIVATION OF ELECTRONIC ADDRESS';
$labels['resetpassword'] = 'Reset password';
$labels['resetpasswordtitle'] = 'RESET PASSWORD';
$messages['invalidactivationurl'] = 'The activation URL provided is invalid or has expired or your account was previously activated';
$messages['tosnotaccepted'] = 'You must accept the terms and conditions';
$messages['erroractivation'] = 'Error when activating the account';
$messages['accountActivated'] = 'Your account has been successfully activated';
$messages['mobileinstruction'] = 'If you cannot scan the QR code, manually enter the following code in the authentication application.';
$messages['alreadycopied'] = 'The code was copied';
$messages['passwordChanged'] = 'Your password has been reset correctly';
$messages['invalidresetpasswordurl'] = 'The URL provided is invalid or has expired or was previously used';