<?php
$labels['username'] = 'Usuario';
$labels['accepttos'] = 'Acepto los <a href="$urltos" target="_blank">términos y condiciones</a> del servicio';
$labels['password'] = 'Contraseña';
$labels['confirmpassword'] = 'Confirmar contraseña';
$labels['activate'] = 'Activar cuenta';
$labels['add2fa'] = 'Añadir factor de autenticación';
$labels['code'] = 'código';
$labels['activationtitle'] = 'ACTIVACIÓN DE DOMICILIO ELECTRÓNICO';
$labels['resetpassword'] = 'Restablecer contraseña';
$labels['resetpasswordtitle'] = 'RESTABLECER CONTRASEÑA';
$messages['invalidactivationurl'] = 'La URL de activación provista no es válida o ha caducado o su cuenta ya fue activada anteriormente';
$messages['tosnotaccepted'] = 'Debe aceptar los términos y condiciones';
$messages['erroractivation'] = 'Error al activar la cuenta';
$messages['accountActivated'] = 'Su cuenta ha sido activada correctamente';
$messages['mobileinstruction'] = 'Si ud no puede escanear el código QR ingrese el siguiente $linkcode manualmente en la aplicación de autenticación.';
$messages['alreadycopied'] = 'Se copió el código';
$messages['passwordChanged'] = 'Su contraseña se ha restablecido correctamente';
$messages['invalidresetpasswordurl'] = 'La URL provista no es valida o ha caducado o ya fue utilizada anteriormente';